server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=UTC
    username: root
    password: root
  initialization-mode: always

  #Actuzaliza BD en caso de que se realice un cambio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect





